### ISSUE TITLE
Problem with clicking the node after relinking

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#106]
If node is not newly created (in that case it might work), after CTRL+K and moving it to a new parent it is not clickable anymore
_P.S Lot of the following comments are caused by Sasha's incorrectly written CTRL+L instead of CTRL+K_

**Comment by sinisarudan** [comment]
@mprinc : Suggesting: Closing

- CTRL+L (AddLink) is not supported yet, so this should be closed. For more security
mapInteraction.ts's  method is extended with
`  addLink() {
        window.alert("This funcionality is not supported yet");
        return;`

- for RELKINKING (CTRL + K) - tested and there are no problems with it

**Comment by mprinc** [comment]
it is not for adding link but for relinking

**Comment by mprinc** [comment]
it is not for adding link but for relinking edge to another parent

**Comment by mprinc** [comment]
i have to reread this again, and maybe talk with you before answering

**Comment by sinisarudan** [comment]
checked in one occasion and thes bug has manifested, but checking it before that and now soon after that, it is not reproduced

**Comment by sinisarudan** [comment]
by @mprinc -> @sir: fora je izgleda da je to u slucaju kada novi otac nije ima djece prije toga, tako da nije open, dakle izgleda ga treba postaviti na open

**Comment by sinisarudan** [comment]
fixed that the new parent becomes opened. tested.
But, now the new parent looks visually being closed, although vknode was changed. When opening it, the new child shows and IS clickable AT LEAST. So functionally, I have solve the problem, but not visually.
@mprinc , test this issue, by searchin in `` for `relinkNode`.

It starts from `Map.prototype.nodeSelected_WithoutRTBroadcasting` 

at part
```
// changing parent node
	// assuming that there is only one parent
	if(this.knalledgeState.relinkingFrom !== null){ //this is called when we relink this node from old to new parent
```

**Necessarily is to check how it works when broadcasted!**
