### ISSUE TITLE
Developers Pack - Install Procedure

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/KnAllEdge#113]
- make it easy to install all Dev pack - both on Mac & Windows
- @mprinc : required prior to going to Jack

**Comment by mprinc** [comment]
We have to check my windows virtual machine, that is important, and i can try to fix on zhenias. good is that i have now installed and built project from non working system - old laptop - and copy from working laptop - new laptop - that is transfered to old laptop and it works :) now I have to compare them and figure out problems, that should help us a lot to explore

**Comment by mprinc** [comment]
This seems to be pretty stable at the moment, both on Mac and Windows machines
