### ISSUE TITLE
RIMA WHATs Creation

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/KnAllEdge#141]
prevent **users' mistakes on RIMA WHATs creation**:
- adding long string of whats separated with COMMAs, instead of independent whats
 - prevent adding punctuations
- warn them if there is already some similar what
- 💣 not visible/usable until:
 - 👍  whats should be **left-align**
 - word-break should be applied
- problem with long whats demonstrated:
 - ![screen shot 2016-07-04 at 7 24 21 pm](https://cloud.githubusercontent.com/assets/1769627/16567320/951b7858-421d-11e6-9cf7-f4bd18dafe37.png)
 - ![screen shot 2016-07-04 at 7 24 42 pm](https://cloud.githubusercontent.com/assets/1769627/16567324/9e6a493e-421d-11e6-9cd0-8835299cb07b.png)

**Comment by mprinc** [comment]
I hope this will be fixed after fixing width of the right panel

**Comment by sinisarudan** [comment]
@mprinc we can solve it by deleting the long old whats and by **preventing them** in future - with an alert saying how to write short whats
