### ISSUE TITLE
Make HTML page title to reflect name of the map and/or name of the selected node

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#206]
- http://stackoverflow.com/questions/34602806/how-to-change-page-title-in-angular2-router
- https://angular.io/docs/ts/latest/cookbook/set-document-title.html
- http://www.bennadel.com/blog/3050-setting-the-window-document-title-in-angular-2-beta-9.htm

**Comment by sinisarudan** [comment]
OK. but not important ... in which use-case is useful?

**Comment by mprinc** [comment]
When you want to see the title, distinguish among many, when you are
bookmarking it, etc
Not urgent for now
