### ISSUE TITLE
MODERATOR: after disabling moderator mode, next node created should be by user, not impersonated

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#228]

**Comment by sinisarudan** [comment]
@mprinc : "impersonated"? 
it is not impersonated, it continues to be added for active user.
WHat has to be done and it is a but, after turning-off moderator mode, active-user should be set to whoAmi - i.e. logged in user.
OK?

**Comment by mprinc** [comment]
technically yes, in my understanding we are impersonating a person, after finishing, we should be back to ourself :)

**Comment by sinisarudan** [comment]
Fixed by commit caedd60 to reset to loggedInUser (getwhoAmI)
