### ISSUE TITLE
Nodes with lot of text cover each other

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/KnAllEdge#232]
@mprinc urgent! content not usable!

![screen shot 2016-07-28 at 11 25 00 pm](https://cloud.githubusercontent.com/assets/1769627/17230056/abb7906e-551a-11e6-8334-7a8b4c9f04a2.png)

![screen shot 2016-07-28 at 9 40 18 pm](https://cloud.githubusercontent.com/assets/1769627/17230063/b0c0290e-551a-11e6-849d-a04663a59c6a.png)

![screen shot 2016-07-21 at 4 33 18 pm](https://cloud.githubusercontent.com/assets/1769627/17230166/0d057106-551b-11e6-9c9a-7e19a6e59e9f.png)
![screen shot 2016-07-21 at 4 43 43 pm](https://cloud.githubusercontent.com/assets/1769627/17230167/0d1c452a-551b-11e6-859a-ea5b2c9955f6.png)
![screen shot 2016-07-21 at 4 46 31 pm](https://cloud.githubusercontent.com/assets/1769627/17230168/0d292d58-551b-11e6-9b72-afbc89e83658.png)

**Comment by mprinc** [comment]
Duplciate of https://github.com/Cha-OS/KnAllEdge/issues/207
