### ISSUE TITLE
MODERATING: when we switch to moderator, we should switch user to anonymous

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#239]
@sinisarudan Now the problem is that we decorate by default everything as us moderators, and later searching what we said is much wider and wrong in general

**Comment by sinisarudan** [comment]
@mprinc - if you mean switching activeUser, then, required behaviour is not correct. I suggest keeping existing behaviour: we keep activeUser same as loggedIn, until we change it by selecting other user to be active

**Comment by sinisarudan** [comment]
duplicate with #227
