### ISSUE TITLE
VISUAL - make a selected node to be on the top of the z-index

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#241]
otherwise, some nodes are not possible to see

**Comment by sinisarudan** [comment]
That's just a consequence of the problem. The problem is they should be positioned not to overlap and then we won't have to think of their positioning

**Comment by mprinc** [comment]
Yes, the ultimate task is here: https://github.com/Cha-OS/KnAllEdge/issues/207
This is just a temporarly workaround
