### ISSUE TITLE
Forbid deleting node with children

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#259]
@sinisarudan Forbid deleting node with children, or at least STRONGLY ask before deleting, and not let it avoid that prompt even for moderator or keyboard shortcuts.

**Comment by KnowledgeGarden** [comment]
should be admin only!

**Comment by mprinc** [comment]
@KnowledgeGarden, @sinisarudan : yes, that is simple but profound discussion!
We need to address it more at Dubrovnik. We believe that deletion should realize in 

+ forking perspectives
+ generating different opinions
+ etc

But the user that is an owner of the knowledge that should be deleted should have possibility or even right :) to avoid seeing (noise of) knowledge he doesn't care anymore.

**Comment by KnowledgeGarden** [comment]
In an IBIS conversation, you cannot delete a node if it has already elicited responses; here, the crucial aspect to be honored is TRUST. Full stop.  If people get the idea that you can just toss out a branch if you don't like their responses to your node, then you lose the core benefit of the conversation in the first place.  If someone puts up a node and doesn't like the responses to it, then that's just tough shit (to borrow a colorful metaphor). Now, if you change your mind, which people sometimes do, there are options, such as creating a new branch that reflects the new understanding, or even refuting their own branch, with new evidence. If, OTOH, there are no responses, then the delete button  should be visible ONLY to an admin or to the node's author.  Keep in mind that there is an opportunity for an optimistic lock failure, created when someone responds to a node that, in the background, got deleted before the response hit the database.  Trust me, you will not have happy campers for users if that happens very frequently
