### ISSUE TITLE
**HALO** losing positioning after moving around map (maybe because of limited range or closing nodes)

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#33]

**Comment by sinisarudan** [comment]
@mprinc don't understand this and cannot thus reproduce

**Comment by mprinc** [comment]
Tested working well,fixed with commit https://github.com/Cha-OS/KnAllEdge/commit/8e85f6aa4c39adfcb16d6fb0ee4d1cd1700ef8d2

Only minor problem at the moment is that on creation of a new node, helo is positioned a bit to the left
