### ISSUE TITLE
$digest already in progress

### ISSUE THREAD

**Issue by mprinc** [Cha-OS/KnAllEdge#75]
Error `app_bundle.js?1465479612080:32 Uncaught Error: [$rootScope:inprog] $digest already in progress` manifested when we create a node

As far as I know this is not a problem for our execution except it is bothering us. This is just a warning that we are already inside of angular and no need to get inside again. Our code sometimes is executed inside and sometime outside of angular context, and sometimes it is hard to figure out

**Comment by sinisarudan** [comment]
This is **VERY IMPORTANT ISSUE/BUG**!
BECAUSE It causes Material switches and buttons "topPanel OFF/ON" and Presentation Start/Stop to stop reacting on user clicks. Switches keep changing their bound data state, but don't change visually while buttons don't react at all.
it is manifested when we create a first node. Node update and delete don't cause it

**Comment by sinisarudan** [comment]
HOw to deal with it:

1. http://stackoverflow.com/questions/12729122/angularjs-prevent-error-digest-already-in-progress-when-calling-scope-apply
2. https://github.com/angular/angular.js/wiki/Anti-Patterns

**Comment by sinisarudan** [comment]
> P.S. Check why settings (gear) button keeps working while identical topPanel OFF/ON, is affected by this $digest bug!!
reordering these 2 buttons in the code does not change which one is working

**Comment by mprinc** [comment]
closed with #02c4898

**Comment by mprinc** [comment]
closed with #02c4898

**Comment by sinisarudan** [comment]
happens in some (MAYBE) non-crucial cases for ITBA.
it happens

1. when we go to `maps` from a map, over uper-right icons (user & logout)
2. when we open a map from http://localhost:5555/#/maps and then click on any node

**Comment by mprinc** [comment]
@sinisarudan I tested and it seems fine. Try to run it and reopen if there is a problem
