### ISSUE TITLE
test - opening new map from the existing

### ISSUE THREAD

**Issue by sinisarudan** [Cha-OS/KnAllEdge#92]
hmmmm, cini mi se da kada odes na onu strelicu gore desno da se izlogujes, da mozda ostane i stara mapa!? i da se ova nova ucita preko nje, tako vizuelno izgleda, a i puca onda "angular.js:13236 Error: [$rootScope:inprog] $digest already in progress"

**Comment by mprinc** [comment]
That was before a problem, now it just stays open and it is covered with this special issue: https://github.com/Cha-OS/KnAllEdge/issues/121
